### ISSUE TITLE
Issue with DB Connections on starting application

### ISSUE THREAD

**Issue by juev** [juev/prometheus_oracle#8]
After release 0.2.0 if we have error on connection to db, we will stop trying to connect. I think it is correct. But for example, we have issue with db connection on starting application, we will lost all metrics from this db.

We can try connect again and again, until connection not established. But is this correct or not??

**Comment by Seth1u** [comment]
@juev 
I think it is a good idea to print some errors log if we have error on connection to database. 
But you can stop trying to connect after connection to listener of instance:
Let's think in the following cases: we want to retrieve the information on the database for an application, first the application connects to the database with the listener, but the problem that can arise is that the listener of the instance can be started but not the database and similarly the database can be started and not the listener of the database. We should think about in which case and how the exporter will collect the metrics. Another case, the good listener is started, the database is started but in MONTED status, there are certain requests that will not succeed since some oracle views are not accessible in MONTED status of the database. A third case in relation to security for a payment database, we use the SSL listener to connect to the database, if the Wallet is not configured the exporter will not be able to connect to the database. data even if the database is started. Hence the interest to think about a direct connection (sqlplus user / password) if the exporter is installed on the database server.

I'm database administrator and i have already encountered these difficulties when I was developing a supervision application for Oracle databases.

**Comment by juev** [comment]
@Seth1u Thanks for your thoughts.

I already added information about connection error. I think current solution was good.
